Models/MontyHallModel.cs
using System.ComponentModel.DataAnnotations;

namespace MontyHallSimulatorApplication.Models
{
    public class Game
    {
        [Range(1, int.MaxValue, ErrorMessage = "The number of games must be at least 1.")]
        public int NumberOfGames { get; set; }
        public bool SwitchDoors { get; set; }
        public int SwitchWins { get; set; }
        public int StayWins { get; set; }
        public int StayLosses { get; set; }
        public int SwitchLosses { get; set; }
    }

}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MontyHallSimulatorApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Controllers/MontyHallController.cs
using System.Web.Mvc;
using MontyHallSimulatorApplication.Models;
using MontyHallSimulatorApplication.Service;

namespace MontyHallSimulatorApplication.Controllers
{
    public class MontyHallController : Controller
    {
        public ActionResult Index()
        {
            return View(new Game());
        }

        [HttpPost]
        public ActionResult Index(Game gameRequest)
        {
            if (ModelState.IsValid)
            {
                SimulatorService simulator = new SimulatorService();
                Game gameResponse = simulator.PlayGame(gameRequest);
                return View(gameResponse);
            }

            return View();
        }
    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Views/MontyHall/Index.cshtml
@model MontyHallSimulatorApplication.Models.Game

@{
    ViewBag.Title = "Monty Hall Game";
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    <div>
        @Html.LabelFor(model => model.NumberOfGames)
        @Html.TextBoxFor(model => model.NumberOfGames, new { type = "number", min = 1 })
        @Html.ValidationMessageFor(model => model.NumberOfGames)
    </div>
    <div>
        @Html.LabelFor(model => model.SwitchDoors)
        @Html.CheckBoxFor(model => model.SwitchDoors)
    </div>
    <button type="submit">Play Game</button>
}

@if (Model.SwitchDoors && (Model.SwitchWins > 0 || Model.SwitchLosses > 0))
{
    <h3>Results:</h3>
    <p>Switching doors wins: @Model.SwitchWins</p>
    <p>Switching doors losses: @Model.SwitchLosses</p>
}
else if(Model.StayWins > 0 || Model.StayLosses > 0)
{
    <h3>Results:</h3>
    <p>Staying with original door wins: @Model.StayWins</p>
    <p>Staying with original door losses: @Model.StayLosses</p>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Start MontyHall Simulator", "Index", "MontyHall", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>